- src/main/java/moze_intel/projecte/gameObjs/items/RepairTalisman.java
Some tools tend to abort the breaking of a block, when the item is repaired during the swing.
> Don't repair items while swinging them (Repair Talisman)

- src/main/java/moze_intel/projecte/emc/EMCMapper.java
Solves Wrong EMC for Fire Charge and Daylight Detector.
Does NOT Solve the Wrong EMC for Hardened Clay, because that is handled in a different Method and would require major code changes.
> Select the recipe and ingredients with smallest EMC value

- src/main/java/moze_intel/projecte/gameObjs/container/TransmuteContainer.java
- src/main/java/moze_intel/projecte/gameObjs/container/TransmuteTabletContainer.java
- src/main/java/moze_intel/projecte/gameObjs/container/slots/transmuteportable/SlotTabletConsume.java
- src/main/java/moze_intel/projecte/gameObjs/container/slots/trasmute/SlotTableConsume.java
Fixes #378 
The fact that this had to be fixed at 4 places in the code made me worry even more...
I only scanned for uses of the `KleinStar`-Class, so i could have missed some places...
> Don't extract EMC from klein stars twice

- src/main/java/moze_intel/projecte/gameObjs/items/EvertideAmulet.java
- src/main/java/moze_intel/projecte/gameObjs/items/VolcaniteAmulet.java
This allows the evertide and volcanite amulets to function like vanilla buckets. Lava placing requires 32 EMC.
The Evertide is now also able to fill cauldrons.
> Bucket functionality for fluid amulets (partially satisfies #472)

- src/main/java/moze_intel/projecte/PECore.java
- src/main/java/moze_intel/projecte/api/ProjectEAPI.java
- src/main/java/moze_intel/projecte/api/package-info.java
This PR adds the @API annotation onto the ProjectE API.
This means that mods can now safely include the PE API with more safety of mind from conflicts
It enforces that if ProjectE is present, regardless of the API version other addons include, the version provided by ProjectE will be used to process all PE API requests.
Looking to make an addon sometime soon so this'll help resolve conflicts.
> Add @API annotation

- src/main/java/moze_intel/projecte/emc/EMCMapper.java
- src/main/java/moze_intel/projecte/emc/GraphMapper.java
- src/main/java/moze_intel/projecte/emc/NormalizedSimpleStack.java
Fix for #550
This was triggered by the FluidMapper, that tried to set a value for a `null`-Fluid.
(probably milk)
Also:
* Move itemId and metadata to `NormalizedSimpleStack.NSSItem`
* Refactor `Group` to `NSSGroup`
* Add `NormalizedSimpleStack.NSSFluid` for Fluids.
* EMCMapper only adds emc values for `NSSItems`
Tested wit `Mariculture-Deluxe-1.7.10-1.2.4.1` and  `TConstruct-1.7.10-1.8.2a`.
Crash is gone - the rest appeared to behave how it should.
> Fix for #550

- src/main/java/moze_intel/projecte/gameObjs/tiles/DMPedestalTile.java
Fix https://github.com/sinkillerj/ProjectE/issues/586
It was 10x10x10 with the pedestal offset on one side.
Now recentered 9x9x9 like it should've been all along
> Fix DM Pedestal effect boundary. - #586

- src/main/java/moze_intel/projecte/gameObjs/customRecipes/RecipesCovalenceRepair.java
Fix https://github.com/sinkillerj/ProjectE/issues/601
Before this commit:
Repairing items with covalence dust consumed 3 dust all the time, without regard for tool class. Dust was still tier checked (high for diamond, med for iron, etc.)
After this commit:
Original EE2 behavior has been restored. Tools and armor take the number of ingots used to make them to repair. Bows take 3 low, Rods take 1 low, and Shears and Flint and Steel take 1 medium.
Tier checking still present, though higher tier dusts can be used to repair lower tier tool types.
> Fix covalence dust repairing #601

- src/main/java/moze_intel/projecte/PECore.java
- src/main/java/moze_intel/projecte/emc/ThreadReloadEMCMap.java
- src/main/java/moze_intel/projecte/network/commands/ReloadEmcCMD.java
- src/main/java/moze_intel/projecte/network/commands/RemoveEmcCMD.java
- src/main/java/moze_intel/projecte/network/commands/ResetEmcCMD.java
- src/main/java/moze_intel/projecte/network/commands/SetEmcCMD.java
"Fix", as in, don't thread ServerStarting. Still think others shouldn't be registering recipes during that phase, but also, users should be able to have EMC values for their stuff. So, yea.
Also, at the request of @MaPePeR, the thread, along with ServerStarting, logs how long it took to (re)map the EMC values.
Take 2.
> "Fix" #629. Also log how long EMC (re)mapping takes.

- src/main/java/moze_intel/projecte/gameObjs/items/AlchemicalBag.java
- src/main/java/moze_intel/projecte/gameObjs/items/EvertideAmulet.java
- src/main/java/moze_intel/projecte/gameObjs/items/VolcaniteAmulet.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/BlackHoleBand.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/Ignition.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/MindStone.java
- src/main/java/moze_intel/projecte/gameObjs/tiles/AlchChestTile.java
- src/main/java/moze_intel/projecte/utils/WorldHelper.java
- src/main/resources/assets/projecte/lang/en_US.lang
The refactor broke merge compatibility in quite a bit of https://github.com/sinkillerj/ProjectE/pull/603
so here's another pr that does the same that did.
Changes:
* Mind Stone has a pedestal function - draws nearby xp orbs in and stores them on the stone
* Unified all "make entity fly towards this point" code areas (duplicated about 7x) into a WorldHelper method, and move some remote checks to be later so the client sees a smooth animation instead of jumpiness.
* Fix potential block deletion exploit with Volcanite/Evertide, and make the arm swing when placing a liquid
* Ignition Ring ignites TNT (and all derivatives) on right click
* Remove a redundant method and compare square distances instead of real distance, save a Math.sqrt() call every tick.
> Miscellaneous Tweaks 2 - Updated version of PR#603

- src/main/java/moze_intel/projecte/gameObjs/items/TimeWatch.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/HarvestGoddess.java
- *All* IGrowables and IPlantables only can be sped using the Harvest Goddess, none using the TimeWatch
- TimeWatch has short internal blacklist of TE's to not speed to avoid infinite loops. We could autodetect this but it would be hacky and use lots of ASM and probably not be worth the effort to do.
> Updated version of PR#615

- src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkPick.java
- src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkShovel.java
- src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java
Resolve #664 - Fore vein-mining accidentally capturing other blocks, potentially causing infinite loops and crashes.
Resolve #671 - Pickaxe doesn't have vein mining
> Fix #664 and #671

- src/main/java/moze_intel/projecte/gameObjs/items/TimeWatch.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/SWRG.java
Fix #655 SWRG missing a remote check in bauble mode
Fix #656 TimeWatch missing localized messages because of derp and because of Minecraft
Fix #663 TimeWatch ignored vanilla permaday gamerules.
Also made TimeWatch apply its time speedup effect both client and serverside so it looks smooth like it used to in EE2 instead of the sun jumping around. Desyncs should not happen as the server constantly resends the time to the client every 2 seconds or so.
Also - don't know how nobody caught this - the Time Watch on the pedestal didn't respect the config, made it do so.
> Fix #655, #656 and #663

- src/main/java/moze_intel/projecte/emc/ThreadReloadEMCMap.java
- src/main/java/moze_intel/projecte/network/commands/ReloadEmcCMD.java
- src/main/java/moze_intel/projecte/network/commands/RemoveEmcCMD.java
- src/main/java/moze_intel/projecte/network/commands/ResetEmcCMD.java
- src/main/java/moze_intel/projecte/network/commands/SetEmcCMD.java
This now sends the chat messages that the operation was successful at the end of the thread, causing less confusion.
> Fixed #657: Send success chat messages after the thread is done running

- src/main/java/moze_intel/projecte/config/ProjectEConfig.java
- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmuteTabletInventory.java
- src/main/java/moze_intel/projecte/gameObjs/entity/EntityLootBall.java
- src/main/java/moze_intel/projecte/gameObjs/tiles/TransmuteTile.java
- src/main/java/moze_intel/projecte/utils/Comparators.java
- src/main/java/moze_intel/projecte/utils/ItemHelper.java
- src/main/java/moze_intel/projecte/utils/WorldHelper.java
- Lootballs now compact / sort their item list instead of holding a list full of millions of 1-big itemstacks
- Lootballs now seek other lootballs every 3 seconds within 1 block of themselves and merge.
- Added config option to not use lootballs at all (lootballs remain enabled by default). WorldHelper.createLoopDrop will instead compact / sort the item list and then spawn the items one by one (Tests with nova cataclysm show that there really is no performance impact from this on high end computers thanks to the sorting and compacting, low end untested)
- Renamed a comparator to make it clear that it's sorting based on EMC value.
> Major Lootball Improvements

- src/main/java/moze_intel/projecte/emc/EMCMapper.java
- src/main/java/moze_intel/projecte/emc/GraphMapper.java
- src/main/java/moze_intel/projecte/emc/NormalizedSimpleStack.java
- src/main/java/moze_intel/projecte/emc/SimpleGraphMapper.java
- src/main/java/moze_intel/projecte/emc/mappers/LazyMapper.java
Log output for vanilla MC + PE: (Removed the `[HH:MM:SS] [ProjectE Reload EMC Thread/WARN] [ProjectE]: `)
```
EMC Exploit: "0 + 9*minecraft:gold_nugget(371:0) => 1*minecraft:gold_ingot(266:0)" ingredient cost: 2043 fixed value of result: 2048
EMC Exploit: "0 + 1*minecraft:double_plant(175:1) => 2*minecraft:dye(351:13)" ingredient cost: 16 fixed value of result: 32
EMC Exploit: "0 + 0*ProjectE:item.pe_philosophers_stone(4096:0) + 7*minecraft:cactus(81:*) + 1*minecraft:coal(263:*) => 7*minecraft:dye(351:2)" ingredient cost: 88 fixed value of result: 112
EMC Exploit: "0 + 1*minecraft:cactus(81:*) => 1*minecraft:dye(351:2)" ingredient cost: 8 fixed value of result: 16
EMC Exploit: "0 + 1*minecraft:double_plant(175:5) => 2*minecraft:dye(351:9)" ingredient cost: 16 fixed value of result: 32
EMC …
```
> Config option to log known emc exploits and fix dye-exploits

- src/main/java/moze_intel/projecte/PECore.java
- src/main/java/moze_intel/projecte/gameObjs/ObjHandler.java
- src/main/java/moze_intel/projecte/utils/Constants.java
Supersedes #719, sry Kolatra :p
Remove spaces from itemblock, block, TileEntity, and entity names. Fixed relay MK2 being "Realy MK2"
Technical deets -
- ItemBlocks and Blocks share names, simply replace spaces and lowercase all. See code.
- Entities: The entities we have are all transient in nature (lootballs, projectiles, and explosive) - they rarely last longer than 5 minutes at max. Thus I simply renamed them.  They will be lost but unless someone stores valuables in lootballs in 5 minute intervals no one will care :p
- Tile Entities: There is a built in system for renaming where one simply registers multiple names, but specifies a single one that will be saved. Forge will read the old names, but then resave them as the primary name you specify. Easy peasy.
> Internal rename with remapping!

- src/main/java/moze_intel/projecte/gameObjs/items/GemEternalDensity.java
- src/main/java/moze_intel/projecte/utils/EMCHelper.java
- src/main/resources/assets/projecte/lang/en_US.lang
I thought i fixed these in the serverlang pull but guess not.
Also considerably buffed the consumption rate of the gem to match what it was in ee2. Instead of 1 item per tick (ProjectE), halve the stack size each tick (EE2)
> Actually fix GoED localizations and buff speed to match ee2

- src/main/java/moze_intel/projecte/gameObjs/blocks/MatterFurnace.java
- src/main/java/moze_intel/projecte/gameObjs/items/itemEntities/LavaOrb.java
- src/main/java/moze_intel/projecte/gameObjs/items/itemEntities/LensExplosive.java
- src/main/java/moze_intel/projecte/gameObjs/items/itemEntities/LootBallItem.java
- src/main/java/moze_intel/projecte/gameObjs/items/itemEntities/RandomizerProjectile.java
- src/main/java/moze_intel/projecte/gameObjs/items/itemEntities/WaterOrb.java
- src/main/resources/assets/projecte/lang/de_DE.lang
I removed the lava orb, the water orb, the explosive lens, the loot ball, the randomizer orb and the active versions of the matter furnaces from the creative tab because they are useless in the inventory. I also fixed a typo in de_DE.lang and I cleaned up the <code>MatterFurnace</code> class a little bit.
> Remove items from creative tab that shouldn't be there

- src/main/java/moze_intel/projecte/emc/ThreadReloadEMCMap.java
- src/main/java/moze_intel/projecte/handlers/TileEntityHandler.java
Fix #698 and its underlying problem.
TileEntityHandler used to maintain a list of coordinates (!!!!!) of all condensers so it could check the lock slot to make sure it has a valid emc target whenever the EMC mapping shifts. Already you can see the problem. What if you have multiple condensers in different dims at the same coords?
Next, on to the actual issue, which describes only condensers in the command sender's world being rechecked. *If the condenser is not found in the world given, the coordinates are plucked off the handler.* BAD. This handler is trans-dimensional. We just ruined the recheck for some condenser in some other dimension. If this handler ever does more than just recheck lock slots this would be so bad.
What I did was 
1. TileEntityHandler holds hard references to …
> Fix horribly broken TileEntityHandler

- src/main/java/moze_intel/projecte/config/NBTWhitelistParser.java
Put both names of the unstable ingot in the nbt whitelist by default. 
This prevents things like https://www.youtube.com/watch?v=hfuW9lH65-E&t=8m05s happening, where invalid NBT data is condensed and people get screwed over. (The ingot was missing NBT data marking it as Stable)
> Fix the nbt whitelist mistake

- src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkSword.java
Closes #741
The two methods shown override vanilla methods, which are called through a Forge hook/reroute. However, in PEToolBase the Forge hook was overriden so the vanilla method would never be called.
Changes it to override the Forge hook instead of the vanilla method so it actually works now.
> Fix sword digspeed

- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmuteTabletInventory.java
Fixes for #531 and similar.
Cause, according to #531 log:
GUITransmuteTablet.onGuiClose() -> GuiContainer.onGuiClose() -> TransmuteTabletContainer.onContainerClosed() -> TransmuteTablet.closeInventory() -> no remote check => try to write nbt on the client side => crash if the client managed to switch to another item that doesn't have nbt data
> Fix all the numerous transmutation tablet writeToNBT crashes

- src/main/java/moze_intel/projecte/emc/EMCMapper.java
- src/main/java/moze_intel/projecte/emc/GraphMapper.java
- src/main/java/moze_intel/projecte/emc/IValueGenerator.java
- src/main/java/moze_intel/projecte/emc/SimpleGraphMapper.java
- src/main/java/moze_intel/projecte/emc/arithmetics/HiddenFractionArithmetic.java
- src/main/java/moze_intel/projecte/emc/arithmetics/HiddenRationalArithmetic.java
- src/main/java/moze_intel/projecte/emc/valuetranslators/AbstractTranslator.java
- src/main/java/moze_intel/projecte/emc/valuetranslators/FractionToIntegerTranslator.java
- src/test/java/moze_intel/projecte/emc/GraphMapperTest.java
- src/test/java/moze_intel/projecte/emc/HiddenFractionSpecificTest.java
For example: stone and cobblestone slabs will not cause a recipe to not result in an emc value.
> Use fractions internally for items with 0< EMC < 1

- src/main/java/moze_intel/projecte/events/PlayerEvents.java
- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmuteTabletInventory.java
- src/main/java/moze_intel/projecte/gameObjs/items/AlchemicalBag.java
- src/main/java/moze_intel/projecte/gameObjs/items/GemEternalDensity.java
- src/main/java/moze_intel/projecte/network/packets/ClientKnowledgeSyncPKT.java
- src/main/java/moze_intel/projecte/network/packets/ClientSyncBagDataPKT.java
- src/main/java/moze_intel/projecte/playerData/AlchemicalBags.java
- src/main/java/moze_intel/projecte/playerData/IOHandler.java
- src/main/java/moze_intel/projecte/playerData/Transmutation.java
- src/main/java/moze_intel/projecte/utils/PELogger.java
So far:
* Made Gem of Eternal Density spam bag packets a lot less often - bag data as a whole is sent immensely less than the old save code did (once every tick, every player, versus only when it changes, per player). The bandwidth we're saving is awesome.
* Data no longer wipes after dying (design limitation of IEEP's, easy workaround)
* Transmutation Tablet no longer desyncs after you close it
* Fix transmutation sometimes creating duplicate entries
* Fix crash with Tome
> Modifications to bag code post-alpha test

- src/main/java/moze_intel/projecte/emc/arithmetics/HiddenFractionArithmetic.java
- src/test/java/moze_intel/projecte/emc/GraphMapperTest.java
- src/test/java/moze_intel/projecte/emc/HiddenFractionSpecificTest.java
This fixes some emc propagation for fractions:
* Stone slab has internal emc of 1/2
* Something that is made from a single stone slab did not have an internal emc of 1/2. With this fix it has.
~~Don't merge yet: It crashes the [exploit1](https://github.com/sinkillerj/ProjectE/blob/master/src/test/java/moze_intel/projecte/emc/GraphMapperTest.java#L433) and [exploit2](https://github.com/sinkillerj/ProjectE/blob/master/src/test/java/moze_intel/projecte/emc/GraphMapperTest.java#L450) testcases. (Recipes with 1 cobble->2 cobble)~~
I fixed the testcases with a try/catch that should never trigger unless someone really made such a cheaty recipe. I did not notice the testcase running longer than the others, so i think it converges to 0 very fast so it *should not be problem* (thats how problems …
> Fraction emc propagation

- src/main/java/moze_intel/projecte/gameObjs/items/DestructionCatalyst.java
- src/main/java/moze_intel/projecte/gameObjs/items/DiviningRodLow.java
- src/main/java/moze_intel/projecte/gameObjs/items/EvertideAmulet.java
- src/main/java/moze_intel/projecte/gameObjs/items/HyperkineticLens.java
- src/main/java/moze_intel/projecte/gameObjs/items/PhilosophersStone.java
- src/main/java/moze_intel/projecte/gameObjs/items/RepairTalisman.java
- src/main/java/moze_intel/projecte/gameObjs/items/VolcaniteAmulet.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/ArchangelSmite.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/BodyStone.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/HarvestGoddess.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/Ignition.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/LifeStone.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/SWRG.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/SoulStone.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/Zero.java
- src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java
- src/main/java/moze_intel/projecte/gameObjs/tiles/DMPedestalTile.java
- src/main/java/moze_intel/projecte/utils/PlayerHelper.java
I have no idea what I was thinking when I wrote this part of the pedestal code (maybe because it was 2AM most likely). Storing fields into the global item singletons and decrementing them in a non-singleton context = terrible and stupid. Not even, it's just downright incorrect :p
tldr - severe timing issue or race condition if you used more than one pedestal with the same power item anywhere in a server/world. Resolved.
> I can't believe I did this [Needs to be pulled asap]

- src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkShovel.java
- src/main/java/moze_intel/projecte/gameObjs/items/tools/RedShovel.java
- src/main/java/moze_intel/projecte/gameObjs/items/tools/RedStar.java
Simple PR, makes it so that the morningstar and shovel consider clay a valid material to harvest.
I don't have a local copy of the repository, so this is untested. I am also not sure this is all that needs to be done to ensure that they harvest clay properly. The goal was to make the morningstar harvest clay on its 9x9 mode.
In most situations this is slightly convenient but not very important, but when using Pam's Clay where clay worldgens.. everywhere.. well..
Let's just say my enormous underground caverns has a ton of clay floating around, as the morningstar ignores it.
> Adds clay to tools

- src/main/java/moze_intel/projecte/events/PlayerEvents.java
- src/main/java/moze_intel/projecte/playerData/TransmutationProps.java
Fix knowledge re-duping when exiting end (ClonePlayer firing at non-death), add patch to remove duplicated knowledge at startup.
Fixes #836, #832
> Fix knowledge re-duping 

- src/main/java/moze_intel/projecte/emc/SimpleGraphMapper.java
Should "fix" #819 
(not tested with the actual environment of the crash)
> Protect the mapping code from Exceptions in 'valueForConversion'

- src/main/java/moze_intel/projecte/emc/SimpleGraphMapper.java
- src/test/java/moze_intel/projecte/emc/GraphMapperTest.java
Fixes #841 
Instead of comparing `(cost of all ingredients)` with `x*(cost of output result)` it now compares `(cost of all ingredients)/x` with `(cost of output result)`. (`x` = number of output results)
This avoids the overflow in the multiplication.
This only works with the Fraction Arithmetic, but i could not find a way to make it work with Integers in time.
> Fix another ArithmeticException

- src/main/java/moze_intel/projecte/gameObjs/items/rings/LifeStone.java
Not sure if that would ever cause any issues - but now that i stumbled across it i can as well fix it.
> FIX: Life Stone might consume up to 128 EMC, but only requested 64

- src/main/java/moze_intel/projecte/network/PacketHandler.java
I missed the other sendFragmentedEmc method in the CME bugfix. Oops. Fixes #856
> Fix for the other method

- src/main/java/moze_intel/projecte/gameObjs/container/TransmutationContainer.java
Fixes #864 
That fix was easier than i thought.
~~Maybe we need to do that in more containers.~~
A search for `canDragIntoSlot` only shows this and the Gem of eternal density gui.
A rewrite of that item handling in that gui would probably not hurt, though.
> Allow to drag items in inventory when Transmutation GUI is opened

- build.gradle
May cause invocationtargetexceptions if you have these mods in your mods folder in dev environment, your mileage may vary. (Essentially means that you have duplicate mods, as these won't be in that folder but still count).
This pull would also cause NEI to be default present in our dev environments, without needing to add it manually.
> Adds NEI dependencies

- src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkPick.java
- src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java
- src/main/java/moze_intel/projecte/gameObjs/items/tools/RedStar.java
- src/main/java/moze_intel/projecte/utils/ItemHelper.java
> Make the 'isOre' check for OreDictionary name not ignore block metadata

- src/main/java/moze_intel/projecte/PECore.java
- src/main/java/moze_intel/projecte/config/ProjectEConfig.java
- src/main/java/moze_intel/projecte/events/ConnectionHandler.java
- src/main/java/moze_intel/projecte/events/TickEvents.java
- src/main/java/moze_intel/projecte/gameObjs/items/IFireProtector.java
- src/main/java/moze_intel/projecte/gameObjs/items/IFlightProvider.java
- src/main/java/moze_intel/projecte/gameObjs/items/IStepAssister.java
- src/main/java/moze_intel/projecte/gameObjs/items/VolcaniteAmulet.java
- src/main/java/moze_intel/projecte/gameObjs/items/armor/GemChest.java
- src/main/java/moze_intel/projecte/gameObjs/items/armor/GemFeet.java
- src/main/java/moze_intel/projecte/gameObjs/items/armor/GemHelmet.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/Arcana.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/Ignition.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/SWRG.java
- src/main/java/moze_intel/projecte/handlers/PlayerChecks.java
- src/main/java/moze_intel/projecte/network/packets/KeyPressPKT.java
- src/main/java/moze_intel/projecte/utils/EMCHelper.java
- src/main/java/moze_intel/projecte/utils/IFireProtectionItem.java
- src/main/java/moze_intel/projecte/utils/IFlightItem.java
- src/main/java/moze_intel/projecte/utils/IStepAssistItem.java
- src/main/java/moze_intel/projecte/utils/PlayerHelper.java
Resolve #893 with bonus side of refactor
Explication of refactor:
I thought a little and realized just how retarded the PlayerChecks mechanism was. (It was mehhhh already, and got a lot worse when Arcana was added). Big huge complicated thing that multiple items had to do multiple times all over the codebase, just look at the negative/red/removed parts of the diff to get an idea...
The purpose of PlayerChecks was to query mc's player capabilities, query what we said the capabilities should be, and if the two don't match, change mc and optionally send it to the client if needed.
I moved it from trying to juggle around a list of who to check and who not to check (which was basically thrashing a collection over and over) in a server tick event to a player tick event for every player. Now …
> [DONE] Resolve #893 with bonus side of refactor

- src/main/java/moze_intel/projecte/gameObjs/items/RepairTalisman.java
Closes #878 and #885. 
#885 is suboptimally fixed, but it's a step in the right direction (prevents items going missing and reported duping, since it doesn't repair while it contains items). Optimally we'd repair it when those things would not occur, instead of not repairing at all.
> Repair talisman

- src/main/java/moze_intel/projecte/gameObjs/container/TransmutationContainer.java
- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmutationInventory.java
- src/main/java/moze_intel/projecte/network/packets/SearchUpdatePKT.java
Alternative implementation for #955.
Instead of syncing the output slots whenever they change we just send the content of the clicked to the server when its clicked in the client.
What do you think?
(Hacked this together in <20mins before i had to leave - but it passed the singleplayer smoke test)
> Update single output slot when clicked on client

- src/main/java/moze_intel/projecte/gameObjs/container/TransmutationContainer.java
Not sure if thats the best fix - but better than no fix at all.
> [SEVERE] Don't crash when clicking empty Slot in Transmutation GUI

- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmutationInventory.java
Code was written under the assumption that `writeIntoOutputSlot` would only ever be called with valid results from `updateOutputs`... NEI apparently changes that...
For some reason 'scrollwheel up' did write the itemstack into the first output slot on the server, which then allowed the client to pull it out again...  or something like that...
> Another fix for what is causing the scroll wheel dupe in 1.9.2

- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmutationInventory.java
So before you couldn't pull out an item for which you had the exact amount of emc.
> Fix smaller/smaller equals derp

- src/main/java/moze_intel/projecte/api/proxy/ITransmutationProxy.java
- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmutationInventory.java
- src/main/java/moze_intel/projecte/impl/TransmutationProxyImpl.java
- src/main/java/moze_intel/projecte/playerData/Transmutation.java
- src/main/java/moze_intel/projecte/playerData/TransmutationProps.java
I decided to check to see how the performance was impacted by getting rid of the full knowledge cache and replacing it with addKnowledge for each item not currently known. As it turns out, the difference is noticeable but not inhibitingly so. There's a tiny moment of lag right as you learn the tome. After that, what you're left with is a map from which you can remove items, allowing players to unlearn items even with a full set of knowledge.
The only reason I can think of that could be an argument against this is the performance impact, which like I mentioned is minimal.
Would close #970
> Allow unlearning from full knowledge

- src/main/java/moze_intel/projecte/utils/ClientKeyHelper.java
Previously, they only showed the English name.
> [DONE] Fix Keybinding localization

- src/main/java/moze_intel/projecte/emc/NormalizedSimpleStack.java
This method is supposed to return `null` when something goes wrong and not throw exceptions, so the recipe/conversion is just ignored.
Fixes #1106
> [DONE] Catch IllegalArgmentException when trying to create an illegal NSSItem

- src/main/java/moze_intel/projecte/gameObjs/blocks/MatterBlock.java
A player noticed a bug where RM and DM blocks are broken but not returned by the redmatter morningstar, I believe this change should fix the issue.
> Allow Redmatter Morningstar to break RM/DM blocks

- src/main/java/moze_intel/projecte/emc/EMCMapper.java
- src/main/java/moze_intel/projecte/emc/NormalizedSimpleStack.java
- src/main/java/moze_intel/projecte/emc/collector/WildcardSetValueFixCollector.java
- src/main/java/moze_intel/projecte/emc/mappers/customConversions/json/CustomConversion.java
Fixes #1245 
The OreDict entry for logWood uses Wildcard-values and i didn't account for that.
> [1.9] Fix Wildcard in setValue.

- src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java
- src/main/java/moze_intel/projecte/utils/ItemHelper.java
- src/main/java/moze_intel/projecte/utils/WorldHelper.java
Without this commit `numMined` will be reset, when one recursion ends and backtracks to the calling recursion again.
~~This is only a partial solution for #1257. It prevents the crash, but because for some reasons the `world.setBlockToAir()`method is not working it does mine the same block multiple times.~~
Found the problem. The block breaking code was not using the `currentPos` variable properly.
Fixes #1257
> [1.9] Fix harvestVein to properly check numMined for every recursion.

- src/main/java/moze_intel/projecte/utils/ItemHelper.java
I got this crash report in 1.7.10-PE1.10.0. 
http://pastebin.com/q26ZwXrr
This, despite the Entity of LittleMaidMobX is inheriting the EntityPlayer, it is the cause the size of the inventory is 36 or less. As a result of this change, even if the size of the inventory is less than 36, it will not crash.
> Fix crash when player inventory size is not 36

- src/main/java/moze_intel/projecte/gameObjs/items/AlchemicalBag.java
- src/main/java/moze_intel/projecte/gameObjs/items/rings/VoidRing.java
- src/main/java/moze_intel/projecte/impl/AlchBagImpl.java
* Check for NBT, not item damage for Void Rings and Black Hole Band in bags. This allows them to suck items into the bags again.
* Only tick down the Void Ring teleport cooldown when positive. Otherwise it goes negative, and wraps around constantly.
* Fix a wrong null annotation causing a crash on startup. (Color should be null to sync all of them, and the functions handle this correctly.)
> Fix a few bugs

- src/main/java/moze_intel/projecte/api/event/PlayerAttemptCondenserSetEvent.java
- src/main/java/moze_intel/projecte/api/event/PlayerAttemptLearnEvent.java
- src/main/java/moze_intel/projecte/gameObjs/container/CondenserContainer.java
- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmutationInventory.java
Implements #1706 
The general description can be found in the issue above. For the implementation of the AttemptLearnEvent I decided that cancelling transmutation learning would still give the player emc; however, it does not add the item to their "learned" items.
EDIT: One thing I forgot to mention is I have fully tested the code and it works properly. If needed I can push my local repo changes to CompatSkills to a branch on my fork of it so that it is easier to test for you guys.
> Support cancelling learning and setting condenser duplicator item

- build.gradle
- src/main/java/moze_intel/projecte/emc/mappers/CraftTweakerRecipeMapper.java
- src/main/java/moze_intel/projecte/emc/mappers/CraftingMapper.java
The new CraftTweaker mapper is only used for newer versions of CraftTweaker that have their new recipe system.
This preserves compatibility with older versions of CraftTweaker
> CraftTweaker Recipe Mapping

- build.gradle
- src/main/java/moze_intel/projecte/emc/mappers/CraftTweakerRecipeMapper.java
Using the modern CraftTweaker main jar was causing issues with
compilation in a dev environment for some devs. This keeps the
functionality for the CraftTweaker fix, and makes all of us able to
compile again.
> Shifts crafttweaker integration to just use the API

- src/main/java/moze_intel/projecte/emc/FuelMapper.java
- src/main/java/moze_intel/projecte/integration/jei/PEJeiPlugin.java
I'm really really hoping this'll fix it. I can't test, due to not getting the crash when running a client and server on my local machine.
getMinecraftServerInstance() is null when running in certain client/server configurations. Minecraft.getMinecraft() should always exist when a client is running it, which we're checking for.
On top of this, I added a fix for a bug that I noticed while debugging the feature, where the final item in the fuel map would display a recipe going from finalItem -> firstItem due to the wrapping effects of getFuelUpgrade.
> Fix for server-side crash from JEI

- src/main/java/moze_intel/projecte/gameObjs/container/CondenserContainer.java
- src/main/java/moze_intel/projecte/gameObjs/container/CondenserMK2Container.java
- src/main/java/moze_intel/projecte/gameObjs/tiles/CondenserTile.java
- src/main/java/moze_intel/projecte/gameObjs/tiles/WrappedItemHandler.java
- This mostly changes "private" to "protected" in a few places, allowing these things to be accessed by subclasses in external mods
- In CondenserContainer.java line 156, im checking with "instanceof Condenser" instead to allow this to work with subclasses
- In CondenserTile.java line 246, im using "getBlockType()" instead to allow this to work with subclasses
These changes are required for me to create an addon mod with custom condensers (They restrict items by EMC value). Repository for addon found here: https://github.com/zerofall/ProgressiveAlchemy
> Made condenser easier to subclass externally

- src/main/java/moze_intel/projecte/integration/jei/PEJeiPlugin.java
When making changes I had forgotten to double check and test in single player. Apparently even with JEI it doesn't work on the released version. Current dev branch does not crash, but just does not display the Collector Category for fuel upgrades in JEI at all. This fixes that. I also tested a bunch of combinations of client + server as well to make sure this didn't break anything else.
> Fixes Collector Category in Single Player

- src/main/java/moze_intel/projecte/gameObjs/container/PhilosStoneContainer.java
- src/main/java/moze_intel/projecte/integration/jei/PEJeiPlugin.java
Shows the philosopher stone on the left hand side in JEI as a possible type of Crafting Table.
Also changes the PhiloStoneContainer to match how ContainerWorkbench works on closing. As of 1.12 when a Crafting grid is closed (2x2 player or 3x3 crafting table) it returns the items in the gui to the player rather than dropping them on the ground. This makes the philosopher's stone crafting grid do the same.
> Philo stone crafting QoL

- src/main/java/moze_intel/projecte/gameObjs/gui/GUICondenser.java
- src/main/java/moze_intel/projecte/gameObjs/gui/GUICondenserMK2.java
- src/main/java/moze_intel/projecte/gameObjs/gui/GUITransmutation.java
- src/main/java/moze_intel/projecte/utils/Constants.java
- src/main/java/moze_intel/projecte/utils/TransmutationEMCFormatter.java
- src/main/resources/assets/projecte/lang/de_de.lang
- src/main/resources/assets/projecte/lang/en_us.lang
- src/main/resources/assets/projecte/lang/fr_fr.lang
- src/main/resources/assets/projecte/lang/pt_br.lang
- src/main/resources/assets/projecte/lang/ru_ru.lang
- src/main/resources/assets/projecte/lang/uk_ua.lang
Originally the EMC value label on the transmutation table would overflow into and past the forget slot as shown:
However with modern modpacks such a stoneblock that includemods such as roost and RFDimensions, it is getting easier to surpass 1 billion EMC. To fix this I have added abbreviations once the EMC wealth surpasses 1 Billion to clean up the UI:
My code is easily expandable as there are two parallel arrays describing the abbreviations within TransmutationEMCFormatter.java. The number of decimal places are decided through the DecimalFormatter within constants.
> Added abreviations for large EMC values (Transmutation table & Condensers)

- src/main/java/moze_intel/projecte/gameObjs/container/CollectorMK1Container.java
Unlike with `getItemChargeProportion` and `getFuelProgress`, `getItemCharge` is not a number between 0, and 1 even though it is a double. Initially when this line was [written](https://github.com/sinkillerj/ProjectE/commit/6dfbd6cac8f3c505697f41f1f9a645f955b2262a#diff-120d82f9c344e998969504c3c6fbbb3dR73) the 8000 got copy pasted here. But unlike the other two variables, this one does not get multiplied in other locations, or get divided by 8000 again on receiving.
I originally was going to include this fix in #1818, but I decided that it is probably better to keep it separate for readability.
> Fix a copy paste error

- src/main/java/moze_intel/projecte/events/ToolTipEvent.java
- src/main/java/moze_intel/projecte/utils/EMCHelper.java
Shows numbers past MAX_LONG instead of obfuscated text for when the stack size is bigger than max long. This way people do not have to manually calculate how much EMC they have in a stack. Also given the tooltip is just a string it doesn't cause any other calculations to break by changing how the string is calculated.
> Go past MAX_LONG for calculating stack EMC Tooltip

- src/main/java/moze_intel/projecte/gameObjs/items/PhilosophersStone.java
Until I was looking at the formatting and to see if ItemMode supported localizing the mode names for #1824, I was not aware that the Philosopher's Stone even had modes. This makes it more clear by adding the current mode back into the tooltip. My guess is this was lost when it was overwritten to display the information about opening the crafting grid.
> Display mode on Philosopher Stone

- src/main/java/moze_intel/projecte/gameObjs/tiles/CollectorMK1Tile.java
This is basically the same as #1035, except that the target branch has been updated, and the acceptEMC method has been modified to more closely mirror the way the RelayMK1Tile calculates how much EMC is accepted.
I tested in Tekkit classic, and I can confirm that this ability was a feature of collectors. No exploit can happen from this, as the collector only transmits EMC when there is no fuel being upgraded, and no item charging. It also only accepts EMC when it has an item being upgraded, or there is an item charging.
> Collectors accept emc from providers when upgrading/charging. Updated

- src/main/java/moze_intel/projecte/utils/ClientKeyHelper.java
If the button is not on the keyboard such as an extra mouse button, display the same text that would get displayed in the controls menu, rather than displaying "INVALID KEY".
> Fallback to key's display name

- src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotLock.java
Same as #1827 but I missed this and found it while writing #1836 to allow the transmutation inventory to utilize klein stars as extra storage space.
> Fixed another bug from making EMC > int

- src/main/java/moze_intel/projecte/gameObjs/blocks/NovaCataclysm.java
- src/main/java/moze_intel/projecte/gameObjs/blocks/NovaCatalyst.java
Tested and this works now. Default implementation of `onBlockExploded` (not overridden by BlockTNT but is in Block)
```
world.setBlockToAir(pos);
onExplosionDestroy(world, pos, explosion);
```
The issue was that when the blocks got blown up, they were never setting it to air so just infinitely exploded. Now it overrides the same method as BlockTNT overrides to spawn the tnt entity.
> Override correct method for block explosives.

- src/main/java/moze_intel/projecte/integration/jei/PEJeiPlugin.java
- src/main/java/moze_intel/projecte/integration/jei/world_transmute/WorldTransmuteEntry.java
- src/main/java/moze_intel/projecte/integration/jei/world_transmute/WorldTransmuteRecipeCategory.java
- src/main/java/moze_intel/projecte/utils/WorldTransmutations.java
- src/main/resources/assets/projecte/lang/en_us.lang
Moves the JEI recipe wrapper for world transmutation out of the WorldTransmutations class so as to not cause crashes without JEI installed. This could have been done with the Optional interface, except I decided to also revamp the recipe category so that it is more programatic for generating the list of items, rather than having lots of hard coded conditions. It also no longer shows a bunch of blank entries for transmutaions of alternate states of blocks (such as rotated logs or pumpkins).
> Improvements to World Transmutation JEI integration

- src/main/java/moze_intel/projecte/gameObjs/items/ItemMode.java
I was unable to reproduce the crash in #1675, but this should be a preventive measure to fix it crashing if somehow the tag compound becomes null.
> Prevent crash if there is no tag for ItemMode

- src/main/java/moze_intel/projecte/emc/mappers/CraftingMapper.java
- src/main/java/moze_intel/projecte/emc/mappers/RecipeStagesRecipeMapper.java
Allows ProjectE to generate EMC automatically in the case where a recipe is staged.
> Add Mapper for staged recipes (Recipe Stages)

- src/main/java/moze_intel/projecte/handlers/InternalAbilities.java
- src/main/java/moze_intel/projecte/network/packets/SetFlyPKT.java
- src/main/java/moze_intel/projecte/utils/PlayerHelper.java
This pull changes two things in regards to the flying checks.
- If the player was in a gamemode that allowed flying, and now they are not but `shouldPlayerFly()` is still true, it syncs the fact that they are allowed to fly to the client. (This allows players to not have to pickup the ring and put it back down to be able to fly again)
- If a player was in a gamemode that allowed flight, and no longer is set their `isFlying` to the same state as it was before. (Sometimes this has a micro drop of about 1/16 of a block before it makes them flying again, but this is preferable to them just not staying in flight at all)
The one quirk this change does not fix is if you are flying in survival and decide to run `/gamemode survival` then it will take you out of flight and you will still have to …
> Handles changes to gamemode in regards to flight

- src/main/java/moze_intel/projecte/gameObjs/tiles/CollectorMK1Tile.java
If for some reason two fuel items have the same EMC (for example if the EMC was manually set) it would previously stop. Instead of removing the part of the if statement checking upgrade cost. I changed it to `>=` just in case it somehow ends up negative (it shouldn't but it doesn't hurt to check)
> Don't stop fuel upgrade if EMC cost is the same

- src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmutationInventory.java
- src/main/java/moze_intel/projecte/impl/KnowledgeImpl.java
- src/main/java/moze_intel/projecte/utils/ItemHelper.java
Bugs with items showing up more than once (such as the philo stone, klein stars, batteries from mods, etc)
Closes #1642 
Closes #1756 
Closes #1790 
Unlearning bug due to the NBT handling not properly seeing a match and causing it to bug out until a restart.
Closes #1783
> Fixed some items with NBT showing up multiple times in Transmutation GUI

- src/main/resources/data/projecte/recipes/conversions/charcoal_to_coal.json
- src/main/resources/data/projecte/recipes/conversions/coal_to_charcoal.json
EE2 supported converting 4 charcoal to 1 coal. It also had a conversion to go back to charcoal.  This PR adds the necessary recipes.
> Add charcoal Philospher's stone conversions

- src/api/java/moze_intel/projecte/api/mapper/recipe/INSSFakeGroupManager.java
- src/api/java/moze_intel/projecte/api/mapper/recipe/IRecipeTypeMapper.java
- src/api/java/moze_intel/projecte/api/nss/NSSFake.java
- src/main/java/moze_intel/projecte/emc/mappers/recipe/BaseRecipeTypeMapper.java
- src/main/java/moze_intel/projecte/emc/mappers/recipe/CraftingMapper.java
- src/main/java/moze_intel/projecte/emc/mappers/recipe/FallbackRecipeTypeMapper.java
I believe this addresses what you were mentioning on discord @MaPePeR regarding the duplicate conversions for identical NormalizedSimpleStacks, as well as the duplicated recipes in cases when the matching stacks may be in a different order. Opening this as a PR for you to review when you get a chance.
> Improve handling of combined fake ingredients

- src/main/java/moze_intel/projecte/emc/SimpleGraphMapper.java
- src/main/java/moze_intel/projecte/emc/collector/MappingCollector.java
I addressed the first few things in https://github.com/sinkillerj/ProjectE/issues/2133#issuecomment-1008120735, but for the last part about the loop, if I understand correctly:
- for all new ingredients it is getting any existing uses for the ingredient
- removing the old conversion for them.
If it looped the old conversion then it would be removing conversions that might not exist with the new one that is overwriting it I think? So I left it as is for now as I think that may be intended.
> Slight cleanup to conversion validation and potentially performance
