src/main/java/moze_intel/projecte/gameObjs/items/PhilosophersStone.java
Fix for #353.
Needs to be adapted to CataliticLens, DestructionCatalyst, DiviningRod* and MercurialEye
=> Fix Philosophers stone sneak right click

src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmuteTabletInventory.java, src/main/java/moze_intel/projecte/gameObjs/tiles/TransmuteTile.java, src/main/java/moze_intel/projecte/utils/NeiHelper.java
The fact, that i had to make this change at 2 places in the code, makes me worry...
=> Use NEI's `ItemFilter`, fixes #374

src/main/java/moze_intel/projecte/gameObjs/items/MercurialEye.java, src/main/java/moze_intel/projecte/utils/CoordinateBox.java
This is based off #429 and contains all the commits in that PR
I've added some additional fixes:
* Improved targeting in transmute mode when clicking the top or bottom of a block
* Added check to prevent transmuting air in transmute mode
* Added check to prevent transmuting tile entities
* Fixed target block metadata being ignored
* Fixed targeting of normal mode when looking up
=> More improvements to Mercurial Eye

src/main/java/moze_intel/projecte/gameObjs/items/MercurialEye.java, src/main/java/moze_intel/projecte/utils/CoordinateBox.java
The Eye in the transmutation mode used to convert block in front of clicked one, so I moved the focus point inside the block clicked.
=> fixed transmutatiom mode for mercurial eye, removed code duplication

src/main/java/moze_intel/projecte/gameObjs/container/MercurialEyeContainer.java
=> Implemented shift+clicking in Mercurial Eye container, fixes #481

src/main/java/moze_intel/projecte/gameObjs/tiles/CollectorMK1Tile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/DMFurnaceTile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/RMFurnaceTile.java
See the commit messages on the first commit for more details, but this improves interaction and allows automation where previously impossible, specifically:
- Extraction from collector
- Insertion of input items into dm/rm furnace
=> Minor enhancements to automation

src/main/java/moze_intel/projecte/emc/EMCMapper.java, src/main/java/moze_intel/projecte/emc/GraphMapper.java, src/main/java/moze_intel/projecte/emc/NormalizedSimpleStack.java
=> GraphMapper fixes for ID=-1 and Ore with EMC=0

src/main/java/moze_intel/projecte/api/IPedestalItem.java, src/main/java/moze_intel/projecte/config/ProjectEConfig.java, src/main/java/moze_intel/projecte/events/ToolTipEvent.java, src/main/java/moze_intel/projecte/gameObjs/items/EvertideAmulet.java, src/main/java/moze_intel/projecte/gameObjs/items/RepairTalisman.java, src/main/java/moze_intel/projecte/gameObjs/items/TimeWatch.java, src/main/java/moze_intel/projecte/gameObjs/items/VolcaniteAmulet.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/ArchangelSmite.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/BodyStone.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/HarvestGoddess.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/Ignition.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/LifeStone.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/SWRG.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/SoulStone.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/Zero.java, src/main/java/moze_intel/projecte/utils/Utils.java
All read from config now.
Tooltips calculate from config and display message if pedestal functionality is disabled.
=> Make all pedestal cooldowns and bonuses configurable.

src/main/java/moze_intel/projecte/gameObjs/gui/GUITransmute.java, src/main/java/moze_intel/projecte/gameObjs/gui/GUITransmuteTablet.java
=> Right-Clicking clears search bar

src/main/java/moze_intel/projecte/gameObjs/items/rings/LifeStone.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/SoulStone.java
=> Bug squelched - #583

src/main/java/moze_intel/projecte/PECore.java, src/main/java/moze_intel/projecte/emc/ThreadReloadEMCMap.java, src/main/java/moze_intel/projecte/network/commands/ReloadEmcCMD.java, src/main/java/moze_intel/projecte/network/commands/RemoveEmcCMD.java, src/main/java/moze_intel/projecte/network/commands/ResetEmcCMD.java, src/main/java/moze_intel/projecte/network/commands/SetEmcCMD.java
This has been tested in the dev env with all the commands. All seems to work. Let me know if I've missed anything.
=> Offload the EMC remapping to a separate thread. Closes #600.

src/main/java/moze_intel/projecte/gameObjs/ObjHandler.java, src/main/java/moze_intel/projecte/gameObjs/items/EvertideAmulet.java
I was surprised that this wasn't in here already :P
Also cleaned up the Evertide Amulet's implementation of IFluidContainerItem; one less opcode :P
EDIT: Reverted implementing IFluidContainerItem on the Volcanite Amulet. Forgot that Lava was 64 EMC.
=> Allowed the Iron Band to be created with a Volcanite Amulet

src/main/java/moze_intel/projecte/gameObjs/items/armor/GemArmor.java
Fix for another occurence of #583, this time in the gem helmet
=> Fix #583 again, but for Gem Armor

src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkAxe.java, src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkHammer.java, src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkHoe.java, src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkShears.java, src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkShovel.java, src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkSword.java, src/main/java/moze_intel/projecte/gameObjs/items/tools/RedSword.java
Remove all EMC costs for tools. Leave the parameter in for addon items that want to have a cost.
=> Remove costs.

src/main/java/moze_intel/projecte/gameObjs/entity/EntityLavaProjectile.java, src/main/java/moze_intel/projecte/gameObjs/entity/EntityLensProjectile.java, src/main/java/moze_intel/projecte/gameObjs/entity/EntityMobRandomizer.java, src/main/java/moze_intel/projecte/gameObjs/entity/EntityWaterProjectile.java
No more matrix projectiles - die in unloaded chunks and when older than 20 seconds.
Partially resolves #724
=> Fix projectiles hanging in the air

src/main/java/moze_intel/projecte/gameObjs/items/rings/HarvestGoddess.java
- Reference static methods the right way
- Remove unused methods
- Harvest mode removes flowers and nether wart (closes #706)
=> Clean up harvband. Closes #706

src/main/java/moze_intel/projecte/playerData/AlchemicalBags.java
This is an improvement upon https://github.com/sinkillerj/ProjectE/commit/2d9070af577922467898cf6438aa2625228195f1#diff-2cd766109075dfa1fd6fea8aab9a29e3R40
Especially the line linked, which IntelliJ says will NullPointerException during runtime. This is because if the retry fails twice four lines above, the method doesn't do anything, leaving a null reference for getdata that might possibly get containsKey called on it at the linked line. Unless we want the game to crash if the data can't be gotten on a retry, in which we should throw an exception instead of just letting things crash and burn.
I also changed everything to reference the Map<> interface so we can switch Map implementations if we want later. Anyone have any idea why we're using a LinkedHashMap for this and not just a plain …
=> Imporvements to bag diagnostics (!possible NPE's averted!)

src/main/java/moze_intel/projecte/emc/GraphMapper.java
=> Typo fixing

src/main/java/moze_intel/projecte/utils/Comparators.java
=> Fix faulty comparator<ItemStack> logic

src/main/java/moze_intel/projecte/gameObjs/items/GemEternalDensity.java, src/main/java/moze_intel/projecte/gameObjs/items/tools/RedPick.java, src/main/java/moze_intel/projecte/utils/NovaExplosion.java
First shot at fixing things and pull requests. Hopefully this works.
=> Query right drops for nova/lens explosions. Fixes #351.

src/main/java/moze_intel/projecte/api/IAlchBagItem.java, src/main/java/moze_intel/projecte/api/package-info.java, src/main/java/moze_intel/projecte/gameObjs/items/AlchemicalBag.java, src/main/java/moze_intel/projecte/gameObjs/items/GemEternalDensity.java, src/main/java/moze_intel/projecte/gameObjs/items/RepairTalisman.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/BlackHoleBand.java
Bag counterpart of #686. This seems much easier than last time. Someone check me before I wreck me.
=> Separate interface from logic for Alchemical Bag Items

src/main/java/moze_intel/projecte/gameObjs/items/RepairTalisman.java
=> Resolve #773 / #734

src/main/java/moze_intel/projecte/gameObjs/tiles/DMPedestalTile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/TileEmc.java, src/main/java/moze_intel/projecte/utils/WorldHelper.java
=> Resolve #432, #723, #778, and #705

src/main/java/moze_intel/projecte/network/commands/ProjectECMD.java
Like #725 but without removing the copy-paste-stuff.
[This](https://github.com/sinkillerj/ProjectE/blob/88dfcc2ba83cd14e9e9d8a943064b1515215d760/src/main/java/moze_intel/projecte/network/commands/ProjectECMD.java#L74-L139) still makes me cringe, though.
=> Prefix tab completion

src/main/resources/assets/projecte/lang/fr_FR.lang
I completely took over the translations to zero, everything is now up-to-date
I also got a small pleasure on a translation ^^: p
=> BIG update of french languages

src/main/java/moze_intel/projecte/emc/EMCMapper.java
=> Catch mapper exceptions

src/main/resources/assets/projecte/lang/pt_BR.lang
Thanks to MaPePeR it's all fixed :3
=> Missing lines corrected

src/main/java/moze_intel/projecte/emc/pregenerated/PregeneratedEMC.java
Just let the Exception throw. Fixes #876 
The one messing with the pregen file will figure it out, i guess.
=> Don't overwrite broken pregen files

src/main/java/moze_intel/projecte/config/ProjectEConfig.java, src/main/java/moze_intel/projecte/events/TransmutationRenderingEvent.java
* Add optional pulsing to Philstone overlay
=> Comforting pulse :p

src/main/java/moze_intel/projecte/events/PlayerEvents.java, src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmutationInventory.java, src/main/java/moze_intel/projecte/gameObjs/gui/GUITransmutation.java, src/main/java/moze_intel/projecte/gameObjs/items/armor/DMArmor.java, src/main/java/moze_intel/projecte/gameObjs/items/armor/GemArmorBase.java, src/main/java/moze_intel/projecte/gameObjs/items/armor/RMArmor.java, src/main/java/moze_intel/projecte/gameObjs/tiles/AlchChestTile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/DMPedestalTile.java, src/main/java/moze_intel/projecte/impl/IMCHandler.java, src/main/java/moze_intel/projecte/impl/TransmutationProxyImpl.java, src/main/java/moze_intel/projecte/network/commands/ProjectECMD.java, src/main/java/moze_intel/projecte/playerData/TransmutationOffline.java, src/main/java/moze_intel/projecte/utils/WorldHelper.java
* Fix IAlchChestItems NPE when ticking clientside because vanilla sucks (1.7 at least, there's a better method in 1.8). Closes #926
* Fix the Turkish locale concerns brought up in #908 and the Reddit thread. It only affected a minor thing (transmutation search), but hey let's be correct. Changed all non-modid uses of String.toLowerCase to String.toLowerCase(Locale.ROOT) which means lowercase in a locale-insensitive way
* Fix a NPE on login in some cases.
=> [DONE] Fix IAlchChestItems crashing and Turkish locale

src/main/java/moze_intel/projecte/gameObjs/tiles/CondenserMK2Tile.java
=> [Done] Fix Mk2 Condenser not stopping to consume items

src/main/java/moze_intel/projecte/events/ToolTipEvent.java
~~Hopefully. did not test it.~~
Did now test it and it worked how it should.
#905
=> [DONE] use checkedMultiply for stacksize*value in tooltip, fixes #905

src/main/java/moze_intel/projecte/handlers/NEI/NEIWorldTransmuteHandler.java
Shenanigans put it on my master branch, oh well. #910 
[Relevant section that isn't just formatting](https://github.com/sinkillerj/ProjectE/pull/911/files#diff-7a86c578b4e594729bd8f1408f6e112fR115) (line 115-125)
Did formatting at the same time.
=> Philostone NEI "usage" shows world transmutations

src/main/java/moze_intel/projecte/gameObjs/gui/GUIManual.java
Accidentallied the other pull. Here you go!
=> Buttonfix. Again.

src/main/java/moze_intel/projecte/handlers/PlayerChecks.java
=> Lets other mods do flight

src/main/resources/assets/projecte/lang/it_IT.lang
=> [DONE]Update language

src/main/java/moze_intel/projecte/utils/EMCHelper.java
Should fix #989 
I hope i did not miss any weird side effects of this.
=> [DONE/FIX #989] Only assume the item is damaged when there is no emc value for that damage value

src/main/java/moze_intel/projecte/gameObjs/tiles/RMFurnaceTile.java
=> Fuel Matter furnaces from collector and continued smelting

src/main/java/moze_intel/projecte/gameObjs/customRecipes/RecipeShapelessHidden.java
Fixes the crafting EMC issue with klein stars.
=> EMC Crafting fix

src/main/java/moze_intel/projecte/integration/Integration.java
Instead of thinking, I immediately set out to make NEI sided. After I finished and made the PR, I realized I was being an idiot. The error was being caught as it is, it just printed a stacktrace that made it look like it was a problem when it wasn't.
Simple PR that just logs what's actually happening, not some scary CLASS NOT FOUND HELP ME PLEASE AHHHHHHHHHHHH
Example error: http://pastebin.com/3RmuB2eh
=> Descriptive error for NEI serverside

src/main/java/moze_intel/projecte/gameObjs/container/TransmutationContainer.java
=> Use stacktrace to detect NEI's FastTransferManager's scrollwheel

src/main/java/moze_intel/projecte/gameObjs/tiles/AlchChestTile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/CollectorMK1Tile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/CondenserTile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/DMPedestalTile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/RMFurnaceTile.java, src/main/java/moze_intel/projecte/gameObjs/tiles/RelayMK1Tile.java
Fixes #1031 properly... hopefully
=> [DONE] Add `isUsableByPlayer` from TileEntityChest to various TileEntitys

src/api/java/thaumcraft/api/items/IGoggles.java, src/api/java/thaumcraft/api/items/IRevealer.java, src/main/java/moze_intel/projecte/gameObjs/entity/EntitySWRGProjectile.java, src/main/java/moze_intel/projecte/gameObjs/items/armor/GemHelmet.java, src/main/java/moze_intel/projecte/gameObjs/items/armor/RMArmor.java
Updates the Thaumcraft API. Fixes crash with Thaumcraft 5.
=> Update to Thaumcraft 5 API.

build.gradle, src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotOutput.java
Check if requested emc is actually available in Slot.decrStackSize
Also calculate the proper EMC value without ignoring the requested stacksize
Fixes #1104
=> [DONE] Fix Double-Click Exploit #1104

src/main/java/moze_intel/projecte/config/ProjectEConfig.java, src/main/java/moze_intel/projecte/gameObjs/items/armor/GemFeet.java, src/main/java/moze_intel/projecte/handlers/PlayerChecks.java, src/main/java/moze_intel/projecte/network/packets/KeyPressPKT.java, src/main/java/moze_intel/projecte/utils/WorldHelper.java
Improve Gem Boots
Add cooldown for gem boom
Fix reeds not leaving last block
=> Tweaks to Gem gliding, Fix Harv Goddess reeds, Cooldown for Gem Boom

src/main/java/moze_intel/projecte/gameObjs/container/TransmutationContainer.java, src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotUnlearn.java, src/main/java/moze_intel/projecte/gameObjs/tiles/CondenserTile.java
=> Fix unlearn condenser dupe

src/main/java/moze_intel/projecte/PECore.java, src/main/java/moze_intel/projecte/gameObjs/entity/EntityHomingArrow.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/ArchangelSmite.java
This PR is aimed to finally bring the last piece of EE2 feature parity to ProjectE - the Archangel's Smite.
The solution that is there right now needs only minimal tweaking to be workable. However, I wanted something more fancy than "point at target and go", so I tried using some maths to get it to arc. 
It kinda does so...in a weird way. If anyone could give suggestions or possibly contribute code (PR to my fork, and it'll merge when this one gets merged), that would be great!
=> [WIP] Finish ProjectE

src/main/java/moze_intel/projecte/api/proxy/IEMCProxy.java, src/main/java/moze_intel/projecte/impl/EMCProxyImpl.java
This is only a GitHub-editor-commit. Did not check if it compiles or fixes anything... But it should.
=> Fix EMCProxyImpl.hasValue(ItemStack) ignoring Metadata. Fixes #1222

README.md
Not moving myself to former team members.. because I'm pretty sure I'm back.
=> Remove outdated patreon link

src/main/java/moze_intel/projecte/gameObjs/container/MercurialEyeContainer.java, src/main/java/moze_intel/projecte/gameObjs/items/MercurialEye.java
* Fixed crash when putting item in target block slot
* Fixed some of the math onItemUse
Not 100% sure i've got everything right, but at least it's less derpy than right now.
=> 1.12 mercurial eye fixes

src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotInput.java, src/main/java/moze_intel/projecte/gameObjs/container/slots/transmutation/SlotLock.java, src/main/java/moze_intel/projecte/gameObjs/tiles/CollectorMK1Tile.java, src/main/java/moze_intel/projecte/utils/EMCHelper.java
Fixes for various issues where PE made some assumptions when dealing with IItemEmcs and such.
There may be other locations I haven't found yet.
fixes #1632
=> IItemEmc fixes

src/main/java/moze_intel/projecte/gameObjs/items/rings/Arcana.java
Currently it just drops at your feet.
=> Fix snowball having no momentum

src/main/java/moze_intel/projecte/gameObjs/container/TransmutationContainer.java
Starts at 12:00 instead of 10:00. I also made the inner circle for fuel go in a circle, instead of how it currently was of 12:00, 9:00, 3:00, 6:00. Because I believe it looks better to have that match the orientation of the outer circle.
Closes #1572
=> Make the slots go in a circle starting at 12:00

src/main/java/moze_intel/projecte/gameObjs/items/rings/Arcana.java, src/main/java/moze_intel/projecte/gameObjs/items/rings/SWRG.java, src/main/java/moze_intel/projecte/gameObjs/sound/MovingSoundSWRG.java, src/main/java/moze_intel/projecte/proxies/ClientProxy.java
This also adds it for the Ring of Arcana, when it is creating a SWRG projectile.
It mimics how Moving Minecarts have their sound done, so that the sound stops as soon as the projectile dies/hits something. It also gets quieter the further away it is.
I wasn't quite sure where to put the sound class, so if you have somewhere you would like it to be moved before this gets merged just let me know where to move it to.
Edit: ~Currently having the title include WIP while I try to fix a bug (that I remember also existing in EE2) where it plays the sound loudly and annoyingly when you are first opening up a world.~ Fixed
=> Adds back the sound for Swiftwolf's Rending Gale
